
openapi: '3.0.2'
info:
  title: LIU TIANQI Blogs System
  description: this is a blogs system for LIU TIANQI
  version: '1.0'
servers:
  - url: https://localhost:8080
paths:
  /:
    get:
      tags:
        - users
      description: '返回login界面'
      operationId: index
      responses:
        '200':
          description: OK
          content:
            text/html:    
              schema:
                $ref: "#/components/schemas/LoginHtml"
  /home:
    post:
      tags:
        - users
      description: '接受用户登陆信息'
      operationId: blog
      requestBody:
        required: true
        content:
          text/json:
            schema:
              type: "object"
              properties:
                username:
                  type: "string"
                password:
                  type: "string"
      responses:
        '200':
          description: OK
          content:
            text/html:    
              schema:
                $ref: "#/components/schemas/Login"
  /register:
    get:
      tags:
        - users
      description: '返回register界面'
      operationId: getRegisterView
      responses:
        '200':
          description: OK
          content:
            text/html:    
              schema:
                $ref: "#/components/schemas/LoginHtml"
  
    post:
      tags:
        - users
      description: '接受用户注册信息'
      operationId: register
      requestBody:
        required: true
        content:
          text/json:
            schema:
              type: "object"
              properties:
                username:
                  type: "string"
                password:
                  type: "string"
                passwordAgain:
                  type: "string"

      responses:
        '200':
          description: OK
          content:
            text/html:    
              schema:
                $ref: "#/components/schemas/Login"
  /blog:
    get:
      tags:
        - users
      description: '返回blog界面'
      operationId: getBlogView
      responses:
        '200':
          description: OK
          content:
            text/html:    
              schema:
                $ref: "#/components/schemas/LoginHtml"
  /editor:
    post:
      tags:
        - users
      description: '进入编辑界面'
      operationId: editor
      requestBody:
        required: true
        content:
          text/json:
            schema:
              type: "object"
              properties:
                title:
                  type: "string"
                introduction:
                  type: "string"
                contents:
                  type: "string"
                user_id:
                  type: "string"
      responses:
        '200':
          description: OK
          content:
            text/html:    
              schema:
                $ref: "#/components/schemas/Login"  

components:
  schemas:
    LoginHtml:
      type: "string"
    Login:
      type: "object"
      properties:
        username:
          type: "string"
        view:
          type: "string"   