
openapi: '3.0.2'
info:
  title: LIU TIANQI blog system
  description: this is a blog system for LIU TIANQI
  version: '1.0'
servers:
  - url: https://localhost:8080
paths:
  /:
    get:
      tags:
        - users
      description: '返回login界面'
      operationId: getLoginView

      responses:
        '200':
          description: OK
          content:
            text/html:    
              schema:
               type: "string"
               example: "login.html"
    post:
      tags:
        - users
      description: '接受user的login信息,若信息正确则返回blog页面'
      operationId: login

      requestBody:
        required: true
        content:
          text/json:
            schema:
              type: "object"
              properties:
                username:
                  type: "string"
                password:
                  type: "string"
      responses:
        '200':
          description: OK
          content:
            text/html:    
              schema:
               type: "object"
               properties:
                username:
                  type: "string"
                view:
                  type: "string"
                  example: "blog.html"
  /register:
    get:
      tags:
        - users
      description: '返回register界面'
      operationId: getRegisterView

      responses:
        '200':
          description: OK
          content:
            text/html:    
              schema:
                type: "string"
                example: "register.html" 
    post:
      tags:
        - users
      description: '接受user输入信息,若两次password一致则返回blog页面'
      operationId: register
      requestBody:
        required: true
        content:
          text/json:
            schema:
              type: "object"
              properties:
                username:
                  type: "string"
                password:
                  type: "string"
                passwordAgain:
                  type: "string"
      responses:
        '200':
          description: OK
          content:
            text/html:    
              schema:
               type: "object"
               properties:
                username:
                  type: "string"
                view:
                  type: "string"
                  example: "blog.html"

  /blog:
    get:
      tags:
        - blogs
      description: '返回blog界面'
      operationId: getBlogView

      requestBody:
        required: true
        content:
          text/json:
            schema:
                type: "object"
                properties:
                  userId:
                    type: "string"
      responses:
        '200':
          description: OK
          content:
            text/html:    
              schema:
               type: "object"

               properties:
                 username:
                  type: "string"
                 blogs:
                   type: array
                   items:
                      type: "object"

                      properties:
                        title:
                          type: "string"
                        introduction:
                          type: "string"
                        contents:
                          type: "string"
                 view:
                   type: "string"
                   example: "blog.html"

  /editor:
    get:
      tags:
        - blogs
      description: '返回editor界面'
      operationId: getEditView
      requestBody:
        required: true
        content:
          text/json:
            schema:
                type: "object"

                properties:
                  userId:
                    type: "string"
                  blogId:
                    type: "string"
      responses:
        '200':
          description: OK
          content:
            text/html:    
              schema:
                type: "string"
                example: "edit.html" 
    post:
      tags:
        - blogs
      description: '接受user输入的编辑信息,并返回blog页面'
      operationId: editor
      requestBody:
        required: true
        content:
          text/json:
            schema:
              type: "object"
              properties:
                title:
                  type: "string"
                introduction:
                  type: "string"
                contents:
                  type: "string"
      responses:
        '200':
          description: OK
          content:
            text/html:    
              schema:
               type: "object"

               properties:
                 username:
                  type: "string"
                 blogs:
                   type: array
                   items:
                      type: "object"

                      properties:
                        title:
                          type: "string"
                        introduction:
                          type: "string"
                        contents:
                          type: "string"
                 view:
                   type: "string"
                   example: "blog.html"

  /delete:
    get:
      tags:
        - blogs
      description: '接受删除blog的信息，并返回新的blog页面'
      operationId: deleteBlog
      requestBody:
        required: true
        content:
          text/json:
            schema:
                type: "object"
                properties:
                  userId:
                    type: "string"
                  blogId:
                    type: "string"
      responses:
        '200':
          description: OK
          content:
            text/html:    
              schema:
               type: "object"

               properties:
                 username:
                  type: "string"
                 blogs:
                   type: array
                   items:
                      type: "object"

                      properties:
                        title:
                          type: "string"
                        introduction:
                          type: "string"
                        contents:
                          type: "string"
                 view:
                   type: "string"
                   example: "blog.html"

  /update:
    get:
      tags:
        - blogs
      description: '返回更新页面'
      operationId: updateBlog
      requestBody:
        required: true
        content:
          text/json:
            schema:
                type: "object"
                properties:
                  userId:
                    type: "string"
                  blogId:
                    type: "string"
      responses:
        '200':
          description: OK
          content:
            text/html:    
              schema:
                type: "string"
                example: "edit.html" 

    post:
      tags:
        - blogs
      description: '接受user的update信息,并返回blog页面'
      operationId: update
      requestBody:
        required: true
        content:
          text/json:
            schema:
              type: "object"
              properties:
                title:
                  type: "string"
                introduction:
                  type: "string"
                content:
                  type: "string"
      responses:
        '200':
          description: OK
          content:
            text/html:    
              schema:
               type: "object"

               properties:
                 username:
                  type: "string"
                 blogs:
                   type: array
                   items:
                      type: "object"

                      properties:
                        title:
                          type: "string"
                        introduction:
                          type: "string"
                        contents:
                          type: "string"
                 view:
                   type: "string"
                   example: "blog.html"